name: CI/CD on push to master

on:
  push:
    branch: [ master ]


jobs:
  deploy-cpanel:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Setup files
        uses: actions/checkout@v2.3.2
      
      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Build Project
        run: |
          echo "Build React App"
          npm ci
          npm run build

      - name: File Transfer Protocol
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
          ftp_host: ${{ secrets.FTP_HOST }}
          ftp_username:  ${{ secrets.FTP_USERNAME }}
          ftp_password: ${{ secrets.FTP_PASSWORD }}
          local_source_dir: "build"
          dist_target_dir: "/public_html"
          only_newer: "true"