name: CI/CD on push to master
on:
  push:
    branch: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup files
        uses: actions/checkout@v2.3.2
      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Build Project
        run: |
          echo "Build React App"
          npm ci
          npm run build
      - name: Temporary save build files
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build/

  deploy-cpanel:
    name: Deployment
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup files
        uses: actions/checkout@v2.3.2

      - name: Retrieve saved build files
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: build/

      - name: check all files
        run: ls -al

      - name: File Transfer Protocol
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: "./build/"
          server-dir: "./public_html/"
